// Generated by gencpp from file laser_mapper/InitialTransform.msg
// DO NOT EDIT!


#ifndef LASER_MAPPER_MESSAGE_INITIALTRANSFORM_H
#define LASER_MAPPER_MESSAGE_INITIALTRANSFORM_H

#include <ros/service_traits.h>


#include <laser_mapper/InitialTransformRequest.h>
#include <laser_mapper/InitialTransformResponse.h>


namespace laser_mapper
{

struct InitialTransform
{

typedef InitialTransformRequest Request;
typedef InitialTransformResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitialTransform
} // namespace laser_mapper


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::laser_mapper::InitialTransform > {
  static const char* value()
  {
    return "ed4c4e4224ec161139370ee82d9ed7da";
  }

  static const char* value(const ::laser_mapper::InitialTransform&) { return value(); }
};

template<>
struct DataType< ::laser_mapper::InitialTransform > {
  static const char* value()
  {
    return "laser_mapper/InitialTransform";
  }

  static const char* value(const ::laser_mapper::InitialTransform&) { return value(); }
};


// service_traits::MD5Sum< ::laser_mapper::InitialTransformRequest> should match 
// service_traits::MD5Sum< ::laser_mapper::InitialTransform > 
template<>
struct MD5Sum< ::laser_mapper::InitialTransformRequest>
{
  static const char* value()
  {
    return MD5Sum< ::laser_mapper::InitialTransform >::value();
  }
  static const char* value(const ::laser_mapper::InitialTransformRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_mapper::InitialTransformRequest> should match 
// service_traits::DataType< ::laser_mapper::InitialTransform > 
template<>
struct DataType< ::laser_mapper::InitialTransformRequest>
{
  static const char* value()
  {
    return DataType< ::laser_mapper::InitialTransform >::value();
  }
  static const char* value(const ::laser_mapper::InitialTransformRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::laser_mapper::InitialTransformResponse> should match 
// service_traits::MD5Sum< ::laser_mapper::InitialTransform > 
template<>
struct MD5Sum< ::laser_mapper::InitialTransformResponse>
{
  static const char* value()
  {
    return MD5Sum< ::laser_mapper::InitialTransform >::value();
  }
  static const char* value(const ::laser_mapper::InitialTransformResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_mapper::InitialTransformResponse> should match 
// service_traits::DataType< ::laser_mapper::InitialTransform > 
template<>
struct DataType< ::laser_mapper::InitialTransformResponse>
{
  static const char* value()
  {
    return DataType< ::laser_mapper::InitialTransform >::value();
  }
  static const char* value(const ::laser_mapper::InitialTransformResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LASER_MAPPER_MESSAGE_INITIALTRANSFORM_H
