// Generated by gencpp from file laser_mapper/LoadTrajectory.msg
// DO NOT EDIT!


#ifndef LASER_MAPPER_MESSAGE_LOADTRAJECTORY_H
#define LASER_MAPPER_MESSAGE_LOADTRAJECTORY_H

#include <ros/service_traits.h>


#include <laser_mapper/LoadTrajectoryRequest.h>
#include <laser_mapper/LoadTrajectoryResponse.h>


namespace laser_mapper
{

struct LoadTrajectory
{

typedef LoadTrajectoryRequest Request;
typedef LoadTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadTrajectory
} // namespace laser_mapper


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::laser_mapper::LoadTrajectory > {
  static const char* value()
  {
    return "a1f82596372c52a517e1fe32d1e998e8";
  }

  static const char* value(const ::laser_mapper::LoadTrajectory&) { return value(); }
};

template<>
struct DataType< ::laser_mapper::LoadTrajectory > {
  static const char* value()
  {
    return "laser_mapper/LoadTrajectory";
  }

  static const char* value(const ::laser_mapper::LoadTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::laser_mapper::LoadTrajectoryRequest> should match 
// service_traits::MD5Sum< ::laser_mapper::LoadTrajectory > 
template<>
struct MD5Sum< ::laser_mapper::LoadTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::laser_mapper::LoadTrajectory >::value();
  }
  static const char* value(const ::laser_mapper::LoadTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_mapper::LoadTrajectoryRequest> should match 
// service_traits::DataType< ::laser_mapper::LoadTrajectory > 
template<>
struct DataType< ::laser_mapper::LoadTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::laser_mapper::LoadTrajectory >::value();
  }
  static const char* value(const ::laser_mapper::LoadTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::laser_mapper::LoadTrajectoryResponse> should match 
// service_traits::MD5Sum< ::laser_mapper::LoadTrajectory > 
template<>
struct MD5Sum< ::laser_mapper::LoadTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::laser_mapper::LoadTrajectory >::value();
  }
  static const char* value(const ::laser_mapper::LoadTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_mapper::LoadTrajectoryResponse> should match 
// service_traits::DataType< ::laser_mapper::LoadTrajectory > 
template<>
struct DataType< ::laser_mapper::LoadTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::laser_mapper::LoadTrajectory >::value();
  }
  static const char* value(const ::laser_mapper::LoadTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LASER_MAPPER_MESSAGE_LOADTRAJECTORY_H
