// Generated by gencpp from file laser_mapper/LoadVTKMap.msg
// DO NOT EDIT!


#ifndef LASER_MAPPER_MESSAGE_LOADVTKMAP_H
#define LASER_MAPPER_MESSAGE_LOADVTKMAP_H

#include <ros/service_traits.h>


#include <laser_mapper/LoadVTKMapRequest.h>
#include <laser_mapper/LoadVTKMapResponse.h>


namespace laser_mapper
{

struct LoadVTKMap
{

typedef LoadVTKMapRequest Request;
typedef LoadVTKMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadVTKMap
} // namespace laser_mapper


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::laser_mapper::LoadVTKMap > {
  static const char* value()
  {
    return "030824f52a0628ead956fb9d67e66ae9";
  }

  static const char* value(const ::laser_mapper::LoadVTKMap&) { return value(); }
};

template<>
struct DataType< ::laser_mapper::LoadVTKMap > {
  static const char* value()
  {
    return "laser_mapper/LoadVTKMap";
  }

  static const char* value(const ::laser_mapper::LoadVTKMap&) { return value(); }
};


// service_traits::MD5Sum< ::laser_mapper::LoadVTKMapRequest> should match 
// service_traits::MD5Sum< ::laser_mapper::LoadVTKMap > 
template<>
struct MD5Sum< ::laser_mapper::LoadVTKMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::laser_mapper::LoadVTKMap >::value();
  }
  static const char* value(const ::laser_mapper::LoadVTKMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_mapper::LoadVTKMapRequest> should match 
// service_traits::DataType< ::laser_mapper::LoadVTKMap > 
template<>
struct DataType< ::laser_mapper::LoadVTKMapRequest>
{
  static const char* value()
  {
    return DataType< ::laser_mapper::LoadVTKMap >::value();
  }
  static const char* value(const ::laser_mapper::LoadVTKMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::laser_mapper::LoadVTKMapResponse> should match 
// service_traits::MD5Sum< ::laser_mapper::LoadVTKMap > 
template<>
struct MD5Sum< ::laser_mapper::LoadVTKMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::laser_mapper::LoadVTKMap >::value();
  }
  static const char* value(const ::laser_mapper::LoadVTKMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_mapper::LoadVTKMapResponse> should match 
// service_traits::DataType< ::laser_mapper::LoadVTKMap > 
template<>
struct DataType< ::laser_mapper::LoadVTKMapResponse>
{
  static const char* value()
  {
    return DataType< ::laser_mapper::LoadVTKMap >::value();
  }
  static const char* value(const ::laser_mapper::LoadVTKMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LASER_MAPPER_MESSAGE_LOADVTKMAP_H
