// Generated by gencpp from file laser_mapper/LoopClosure.msg
// DO NOT EDIT!


#ifndef LASER_MAPPER_MESSAGE_LOOPCLOSURE_H
#define LASER_MAPPER_MESSAGE_LOOPCLOSURE_H

#include <ros/service_traits.h>


#include <laser_mapper/LoopClosureRequest.h>
#include <laser_mapper/LoopClosureResponse.h>


namespace laser_mapper
{

struct LoopClosure
{

typedef LoopClosureRequest Request;
typedef LoopClosureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoopClosure
} // namespace laser_mapper


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::laser_mapper::LoopClosure > {
  static const char* value()
  {
    return "2bfd8abab66078a46d6c266f42293b3d";
  }

  static const char* value(const ::laser_mapper::LoopClosure&) { return value(); }
};

template<>
struct DataType< ::laser_mapper::LoopClosure > {
  static const char* value()
  {
    return "laser_mapper/LoopClosure";
  }

  static const char* value(const ::laser_mapper::LoopClosure&) { return value(); }
};


// service_traits::MD5Sum< ::laser_mapper::LoopClosureRequest> should match 
// service_traits::MD5Sum< ::laser_mapper::LoopClosure > 
template<>
struct MD5Sum< ::laser_mapper::LoopClosureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::laser_mapper::LoopClosure >::value();
  }
  static const char* value(const ::laser_mapper::LoopClosureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_mapper::LoopClosureRequest> should match 
// service_traits::DataType< ::laser_mapper::LoopClosure > 
template<>
struct DataType< ::laser_mapper::LoopClosureRequest>
{
  static const char* value()
  {
    return DataType< ::laser_mapper::LoopClosure >::value();
  }
  static const char* value(const ::laser_mapper::LoopClosureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::laser_mapper::LoopClosureResponse> should match 
// service_traits::MD5Sum< ::laser_mapper::LoopClosure > 
template<>
struct MD5Sum< ::laser_mapper::LoopClosureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::laser_mapper::LoopClosure >::value();
  }
  static const char* value(const ::laser_mapper::LoopClosureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_mapper::LoopClosureResponse> should match 
// service_traits::DataType< ::laser_mapper::LoopClosure > 
template<>
struct DataType< ::laser_mapper::LoopClosureResponse>
{
  static const char* value()
  {
    return DataType< ::laser_mapper::LoopClosure >::value();
  }
  static const char* value(const ::laser_mapper::LoopClosureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LASER_MAPPER_MESSAGE_LOOPCLOSURE_H
