// Generated by gencpp from file wireless_network_msgs/RequestRSS_Load_PCResponse.msg
// DO NOT EDIT!


#ifndef WIRELESS_NETWORK_MSGS_MESSAGE_REQUESTRSS_LOAD_PCRESPONSE_H
#define WIRELESS_NETWORK_MSGS_MESSAGE_REQUESTRSS_LOAD_PCRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wireless_network_msgs
{
template <class ContainerAllocator>
struct RequestRSS_Load_PCResponse_
{
  typedef RequestRSS_Load_PCResponse_<ContainerAllocator> Type;

  RequestRSS_Load_PCResponse_()
    : status(false)  {
    }
  RequestRSS_Load_PCResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::wireless_network_msgs::RequestRSS_Load_PCResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wireless_network_msgs::RequestRSS_Load_PCResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RequestRSS_Load_PCResponse_

typedef ::wireless_network_msgs::RequestRSS_Load_PCResponse_<std::allocator<void> > RequestRSS_Load_PCResponse;

typedef boost::shared_ptr< ::wireless_network_msgs::RequestRSS_Load_PCResponse > RequestRSS_Load_PCResponsePtr;
typedef boost::shared_ptr< ::wireless_network_msgs::RequestRSS_Load_PCResponse const> RequestRSS_Load_PCResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wireless_network_msgs::RequestRSS_Load_PCResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wireless_network_msgs::RequestRSS_Load_PCResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wireless_network_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'wireless_network_msgs': ['/home/elliottwhite/turtlebot2_wss/turtlebot_navigation_ws/src/tradr-msgs/wireless_network_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wireless_network_msgs::RequestRSS_Load_PCResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wireless_network_msgs::RequestRSS_Load_PCResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wireless_network_msgs::RequestRSS_Load_PCResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wireless_network_msgs::RequestRSS_Load_PCResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wireless_network_msgs::RequestRSS_Load_PCResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wireless_network_msgs::RequestRSS_Load_PCResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wireless_network_msgs::RequestRSS_Load_PCResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::wireless_network_msgs::RequestRSS_Load_PCResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::wireless_network_msgs::RequestRSS_Load_PCResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wireless_network_msgs/RequestRSS_Load_PCResponse";
  }

  static const char* value(const ::wireless_network_msgs::RequestRSS_Load_PCResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wireless_network_msgs::RequestRSS_Load_PCResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
bool status\n\
\n\
\n\
";
  }

  static const char* value(const ::wireless_network_msgs::RequestRSS_Load_PCResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wireless_network_msgs::RequestRSS_Load_PCResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RequestRSS_Load_PCResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wireless_network_msgs::RequestRSS_Load_PCResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wireless_network_msgs::RequestRSS_Load_PCResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WIRELESS_NETWORK_MSGS_MESSAGE_REQUESTRSS_LOAD_PCRESPONSE_H
