// Generated by gencpp from file wireless_network_msgs/RequestRSS_Publish_PC.msg
// DO NOT EDIT!


#ifndef WIRELESS_NETWORK_MSGS_MESSAGE_REQUESTRSS_PUBLISH_PC_H
#define WIRELESS_NETWORK_MSGS_MESSAGE_REQUESTRSS_PUBLISH_PC_H

#include <ros/service_traits.h>


#include <wireless_network_msgs/RequestRSS_Publish_PCRequest.h>
#include <wireless_network_msgs/RequestRSS_Publish_PCResponse.h>


namespace wireless_network_msgs
{

struct RequestRSS_Publish_PC
{

typedef RequestRSS_Publish_PCRequest Request;
typedef RequestRSS_Publish_PCResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RequestRSS_Publish_PC
} // namespace wireless_network_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wireless_network_msgs::RequestRSS_Publish_PC > {
  static const char* value()
  {
    return "be35b97a626a98d93d3670b842cadba3";
  }

  static const char* value(const ::wireless_network_msgs::RequestRSS_Publish_PC&) { return value(); }
};

template<>
struct DataType< ::wireless_network_msgs::RequestRSS_Publish_PC > {
  static const char* value()
  {
    return "wireless_network_msgs/RequestRSS_Publish_PC";
  }

  static const char* value(const ::wireless_network_msgs::RequestRSS_Publish_PC&) { return value(); }
};


// service_traits::MD5Sum< ::wireless_network_msgs::RequestRSS_Publish_PCRequest> should match 
// service_traits::MD5Sum< ::wireless_network_msgs::RequestRSS_Publish_PC > 
template<>
struct MD5Sum< ::wireless_network_msgs::RequestRSS_Publish_PCRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wireless_network_msgs::RequestRSS_Publish_PC >::value();
  }
  static const char* value(const ::wireless_network_msgs::RequestRSS_Publish_PCRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wireless_network_msgs::RequestRSS_Publish_PCRequest> should match 
// service_traits::DataType< ::wireless_network_msgs::RequestRSS_Publish_PC > 
template<>
struct DataType< ::wireless_network_msgs::RequestRSS_Publish_PCRequest>
{
  static const char* value()
  {
    return DataType< ::wireless_network_msgs::RequestRSS_Publish_PC >::value();
  }
  static const char* value(const ::wireless_network_msgs::RequestRSS_Publish_PCRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wireless_network_msgs::RequestRSS_Publish_PCResponse> should match 
// service_traits::MD5Sum< ::wireless_network_msgs::RequestRSS_Publish_PC > 
template<>
struct MD5Sum< ::wireless_network_msgs::RequestRSS_Publish_PCResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wireless_network_msgs::RequestRSS_Publish_PC >::value();
  }
  static const char* value(const ::wireless_network_msgs::RequestRSS_Publish_PCResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wireless_network_msgs::RequestRSS_Publish_PCResponse> should match 
// service_traits::DataType< ::wireless_network_msgs::RequestRSS_Publish_PC > 
template<>
struct DataType< ::wireless_network_msgs::RequestRSS_Publish_PCResponse>
{
  static const char* value()
  {
    return DataType< ::wireless_network_msgs::RequestRSS_Publish_PC >::value();
  }
  static const char* value(const ::wireless_network_msgs::RequestRSS_Publish_PCResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WIRELESS_NETWORK_MSGS_MESSAGE_REQUESTRSS_PUBLISH_PC_H
