// Generated by gencpp from file wireless_network_msgs/Request_GPR_resetRequest.msg
// DO NOT EDIT!


#ifndef WIRELESS_NETWORK_MSGS_MESSAGE_REQUEST_GPR_RESETREQUEST_H
#define WIRELESS_NETWORK_MSGS_MESSAGE_REQUEST_GPR_RESETREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int32.h>

namespace wireless_network_msgs
{
template <class ContainerAllocator>
struct Request_GPR_resetRequest_
{
  typedef Request_GPR_resetRequest_<ContainerAllocator> Type;

  Request_GPR_resetRequest_()
    : id_source()  {
    }
  Request_GPR_resetRequest_(const ContainerAllocator& _alloc)
    : id_source(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int32_<ContainerAllocator>  _id_source_type;
  _id_source_type id_source;





  typedef boost::shared_ptr< ::wireless_network_msgs::Request_GPR_resetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wireless_network_msgs::Request_GPR_resetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Request_GPR_resetRequest_

typedef ::wireless_network_msgs::Request_GPR_resetRequest_<std::allocator<void> > Request_GPR_resetRequest;

typedef boost::shared_ptr< ::wireless_network_msgs::Request_GPR_resetRequest > Request_GPR_resetRequestPtr;
typedef boost::shared_ptr< ::wireless_network_msgs::Request_GPR_resetRequest const> Request_GPR_resetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wireless_network_msgs::Request_GPR_resetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wireless_network_msgs::Request_GPR_resetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wireless_network_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'wireless_network_msgs': ['/home/elliottwhite/turtlebot2_wss/turtlebot_navigation_ws/src/tradr-msgs/wireless_network_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wireless_network_msgs::Request_GPR_resetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wireless_network_msgs::Request_GPR_resetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wireless_network_msgs::Request_GPR_resetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wireless_network_msgs::Request_GPR_resetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wireless_network_msgs::Request_GPR_resetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wireless_network_msgs::Request_GPR_resetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wireless_network_msgs::Request_GPR_resetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "833819c4687d26c1501ed0a7ab1aebec";
  }

  static const char* value(const ::wireless_network_msgs::Request_GPR_resetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x833819c4687d26c1ULL;
  static const uint64_t static_value2 = 0x501ed0a7ab1aebecULL;
};

template<class ContainerAllocator>
struct DataType< ::wireless_network_msgs::Request_GPR_resetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wireless_network_msgs/Request_GPR_resetRequest";
  }

  static const char* value(const ::wireless_network_msgs::Request_GPR_resetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wireless_network_msgs::Request_GPR_resetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
std_msgs/Int32 id_source\n\
\n\
================================================================================\n\
MSG: std_msgs/Int32\n\
int32 data\n\
";
  }

  static const char* value(const ::wireless_network_msgs::Request_GPR_resetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wireless_network_msgs::Request_GPR_resetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id_source);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Request_GPR_resetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wireless_network_msgs::Request_GPR_resetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wireless_network_msgs::Request_GPR_resetRequest_<ContainerAllocator>& v)
  {
    s << indent << "id_source: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.id_source);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WIRELESS_NETWORK_MSGS_MESSAGE_REQUEST_GPR_RESETREQUEST_H
