// Generated by gencpp from file wireless_network_msgs/RequestRSS_PC_Point.msg
// DO NOT EDIT!


#ifndef WIRELESS_NETWORK_MSGS_MESSAGE_REQUESTRSS_PC_POINT_H
#define WIRELESS_NETWORK_MSGS_MESSAGE_REQUESTRSS_PC_POINT_H

#include <ros/service_traits.h>


#include <wireless_network_msgs/RequestRSS_PC_PointRequest.h>
#include <wireless_network_msgs/RequestRSS_PC_PointResponse.h>


namespace wireless_network_msgs
{

struct RequestRSS_PC_Point
{

typedef RequestRSS_PC_PointRequest Request;
typedef RequestRSS_PC_PointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RequestRSS_PC_Point
} // namespace wireless_network_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wireless_network_msgs::RequestRSS_PC_Point > {
  static const char* value()
  {
    return "c2b2aa1a5c63edd72f88325c073d2e78";
  }

  static const char* value(const ::wireless_network_msgs::RequestRSS_PC_Point&) { return value(); }
};

template<>
struct DataType< ::wireless_network_msgs::RequestRSS_PC_Point > {
  static const char* value()
  {
    return "wireless_network_msgs/RequestRSS_PC_Point";
  }

  static const char* value(const ::wireless_network_msgs::RequestRSS_PC_Point&) { return value(); }
};


// service_traits::MD5Sum< ::wireless_network_msgs::RequestRSS_PC_PointRequest> should match 
// service_traits::MD5Sum< ::wireless_network_msgs::RequestRSS_PC_Point > 
template<>
struct MD5Sum< ::wireless_network_msgs::RequestRSS_PC_PointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wireless_network_msgs::RequestRSS_PC_Point >::value();
  }
  static const char* value(const ::wireless_network_msgs::RequestRSS_PC_PointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wireless_network_msgs::RequestRSS_PC_PointRequest> should match 
// service_traits::DataType< ::wireless_network_msgs::RequestRSS_PC_Point > 
template<>
struct DataType< ::wireless_network_msgs::RequestRSS_PC_PointRequest>
{
  static const char* value()
  {
    return DataType< ::wireless_network_msgs::RequestRSS_PC_Point >::value();
  }
  static const char* value(const ::wireless_network_msgs::RequestRSS_PC_PointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wireless_network_msgs::RequestRSS_PC_PointResponse> should match 
// service_traits::MD5Sum< ::wireless_network_msgs::RequestRSS_PC_Point > 
template<>
struct MD5Sum< ::wireless_network_msgs::RequestRSS_PC_PointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wireless_network_msgs::RequestRSS_PC_Point >::value();
  }
  static const char* value(const ::wireless_network_msgs::RequestRSS_PC_PointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wireless_network_msgs::RequestRSS_PC_PointResponse> should match 
// service_traits::DataType< ::wireless_network_msgs::RequestRSS_PC_Point > 
template<>
struct DataType< ::wireless_network_msgs::RequestRSS_PC_PointResponse>
{
  static const char* value()
  {
    return DataType< ::wireless_network_msgs::RequestRSS_PC_Point >::value();
  }
  static const char* value(const ::wireless_network_msgs::RequestRSS_PC_PointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WIRELESS_NETWORK_MSGS_MESSAGE_REQUESTRSS_PC_POINT_H
