// Generated by gencpp from file wireless_network_msgs/RequestRSS.msg
// DO NOT EDIT!


#ifndef WIRELESS_NETWORK_MSGS_MESSAGE_REQUESTRSS_H
#define WIRELESS_NETWORK_MSGS_MESSAGE_REQUESTRSS_H

#include <ros/service_traits.h>


#include <wireless_network_msgs/RequestRSSRequest.h>
#include <wireless_network_msgs/RequestRSSResponse.h>


namespace wireless_network_msgs
{

struct RequestRSS
{

typedef RequestRSSRequest Request;
typedef RequestRSSResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RequestRSS
} // namespace wireless_network_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wireless_network_msgs::RequestRSS > {
  static const char* value()
  {
    return "d8423904b521dd22d9d11c6abff995e6";
  }

  static const char* value(const ::wireless_network_msgs::RequestRSS&) { return value(); }
};

template<>
struct DataType< ::wireless_network_msgs::RequestRSS > {
  static const char* value()
  {
    return "wireless_network_msgs/RequestRSS";
  }

  static const char* value(const ::wireless_network_msgs::RequestRSS&) { return value(); }
};


// service_traits::MD5Sum< ::wireless_network_msgs::RequestRSSRequest> should match 
// service_traits::MD5Sum< ::wireless_network_msgs::RequestRSS > 
template<>
struct MD5Sum< ::wireless_network_msgs::RequestRSSRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wireless_network_msgs::RequestRSS >::value();
  }
  static const char* value(const ::wireless_network_msgs::RequestRSSRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wireless_network_msgs::RequestRSSRequest> should match 
// service_traits::DataType< ::wireless_network_msgs::RequestRSS > 
template<>
struct DataType< ::wireless_network_msgs::RequestRSSRequest>
{
  static const char* value()
  {
    return DataType< ::wireless_network_msgs::RequestRSS >::value();
  }
  static const char* value(const ::wireless_network_msgs::RequestRSSRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wireless_network_msgs::RequestRSSResponse> should match 
// service_traits::MD5Sum< ::wireless_network_msgs::RequestRSS > 
template<>
struct MD5Sum< ::wireless_network_msgs::RequestRSSResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wireless_network_msgs::RequestRSS >::value();
  }
  static const char* value(const ::wireless_network_msgs::RequestRSSResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wireless_network_msgs::RequestRSSResponse> should match 
// service_traits::DataType< ::wireless_network_msgs::RequestRSS > 
template<>
struct DataType< ::wireless_network_msgs::RequestRSSResponse>
{
  static const char* value()
  {
    return DataType< ::wireless_network_msgs::RequestRSS >::value();
  }
  static const char* value(const ::wireless_network_msgs::RequestRSSResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WIRELESS_NETWORK_MSGS_MESSAGE_REQUESTRSS_H
