// Generated by gencpp from file wireless_network_msgs/wirelesslink.msg
// DO NOT EDIT!


#ifndef WIRELESS_NETWORK_MSGS_MESSAGE_WIRELESSLINK_H
#define WIRELESS_NETWORK_MSGS_MESSAGE_WIRELESSLINK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace wireless_network_msgs
{
template <class ContainerAllocator>
struct wirelesslink_
{
  typedef wirelesslink_<ContainerAllocator> Type;

  wirelesslink_()
    : header()
    , rssi(0.0)
    , lqi(0)
    , noise(0)
    , id()  {
    }
  wirelesslink_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , rssi(0.0)
    , lqi(0)
    , noise(0)
    , id(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _rssi_type;
  _rssi_type rssi;

   typedef int32_t _lqi_type;
  _lqi_type lqi;

   typedef int32_t _noise_type;
  _noise_type noise;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::wireless_network_msgs::wirelesslink_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wireless_network_msgs::wirelesslink_<ContainerAllocator> const> ConstPtr;

}; // struct wirelesslink_

typedef ::wireless_network_msgs::wirelesslink_<std::allocator<void> > wirelesslink;

typedef boost::shared_ptr< ::wireless_network_msgs::wirelesslink > wirelesslinkPtr;
typedef boost::shared_ptr< ::wireless_network_msgs::wirelesslink const> wirelesslinkConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wireless_network_msgs::wirelesslink_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wireless_network_msgs::wirelesslink_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wireless_network_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'wireless_network_msgs': ['/home/elliottwhite/turtlebot2_wss/turtlebot_navigation_ws/src/tradr-msgs/wireless_network_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wireless_network_msgs::wirelesslink_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wireless_network_msgs::wirelesslink_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wireless_network_msgs::wirelesslink_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wireless_network_msgs::wirelesslink_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wireless_network_msgs::wirelesslink_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wireless_network_msgs::wirelesslink_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wireless_network_msgs::wirelesslink_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b66245439f6c497dfd55043e8bf4332e";
  }

  static const char* value(const ::wireless_network_msgs::wirelesslink_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb66245439f6c497dULL;
  static const uint64_t static_value2 = 0xfd55043e8bf4332eULL;
};

template<class ContainerAllocator>
struct DataType< ::wireless_network_msgs::wirelesslink_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wireless_network_msgs/wirelesslink";
  }

  static const char* value(const ::wireless_network_msgs::wirelesslink_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wireless_network_msgs::wirelesslink_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
#Received Signal Strength (RSS) in dBm\n\
float32 rssi\n\
\n\
#Link Quality of the wireless link in percentage\n\
int32 lqi\n\
\n\
#Noise floor of the wireless link in dBm (only very few NICs provide this correctly)\n\
int32 noise\n\
\n\
#Source id - either AP name, or SSID or the mac address\n\
string id\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::wireless_network_msgs::wirelesslink_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wireless_network_msgs::wirelesslink_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.rssi);
      stream.next(m.lqi);
      stream.next(m.noise);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wirelesslink_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wireless_network_msgs::wirelesslink_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wireless_network_msgs::wirelesslink_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rssi: ";
    Printer<float>::stream(s, indent + "  ", v.rssi);
    s << indent << "lqi: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lqi);
    s << indent << "noise: ";
    Printer<int32_t>::stream(s, indent + "  ", v.noise);
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WIRELESS_NETWORK_MSGS_MESSAGE_WIRELESSLINK_H
