(cl:defpackage nifti_teleop-msg
  (:use )
  (:export
   "<SCANNINGACTION>"
   "SCANNINGACTION"
   "<SCANNINGACTIONFEEDBACK>"
   "SCANNINGACTIONFEEDBACK"
   "<SCANNINGACTIONGOAL>"
   "SCANNINGACTIONGOAL"
   "<SCANNINGACTIONRESULT>"
   "SCANNINGACTIONRESULT"
   "<SCANNINGFEEDBACK>"
   "SCANNINGFEEDBACK"
   "<SCANNINGGOAL>"
   "SCANNINGGOAL"
   "<SCANNINGRESULT>"
   "SCANNINGRESULT"
  ))

