// Generated by gencpp from file laser_mapper_tools/SetPose.msg
// DO NOT EDIT!


#ifndef LASER_MAPPER_TOOLS_MESSAGE_SETPOSE_H
#define LASER_MAPPER_TOOLS_MESSAGE_SETPOSE_H

#include <ros/service_traits.h>


#include <laser_mapper_tools/SetPoseRequest.h>
#include <laser_mapper_tools/SetPoseResponse.h>


namespace laser_mapper_tools
{

struct SetPose
{

typedef SetPoseRequest Request;
typedef SetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPose
} // namespace laser_mapper_tools


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::laser_mapper_tools::SetPose > {
  static const char* value()
  {
    return "3f8930d968a3e84d471dff917bb1cdae";
  }

  static const char* value(const ::laser_mapper_tools::SetPose&) { return value(); }
};

template<>
struct DataType< ::laser_mapper_tools::SetPose > {
  static const char* value()
  {
    return "laser_mapper_tools/SetPose";
  }

  static const char* value(const ::laser_mapper_tools::SetPose&) { return value(); }
};


// service_traits::MD5Sum< ::laser_mapper_tools::SetPoseRequest> should match 
// service_traits::MD5Sum< ::laser_mapper_tools::SetPose > 
template<>
struct MD5Sum< ::laser_mapper_tools::SetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::laser_mapper_tools::SetPose >::value();
  }
  static const char* value(const ::laser_mapper_tools::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_mapper_tools::SetPoseRequest> should match 
// service_traits::DataType< ::laser_mapper_tools::SetPose > 
template<>
struct DataType< ::laser_mapper_tools::SetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::laser_mapper_tools::SetPose >::value();
  }
  static const char* value(const ::laser_mapper_tools::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::laser_mapper_tools::SetPoseResponse> should match 
// service_traits::MD5Sum< ::laser_mapper_tools::SetPose > 
template<>
struct MD5Sum< ::laser_mapper_tools::SetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::laser_mapper_tools::SetPose >::value();
  }
  static const char* value(const ::laser_mapper_tools::SetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_mapper_tools::SetPoseResponse> should match 
// service_traits::DataType< ::laser_mapper_tools::SetPose > 
template<>
struct DataType< ::laser_mapper_tools::SetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::laser_mapper_tools::SetPose >::value();
  }
  static const char* value(const ::laser_mapper_tools::SetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LASER_MAPPER_TOOLS_MESSAGE_SETPOSE_H
