// Generated by gencpp from file nifti_teleop/Acquire.msg
// DO NOT EDIT!


#ifndef NIFTI_TELEOP_MESSAGE_ACQUIRE_H
#define NIFTI_TELEOP_MESSAGE_ACQUIRE_H

#include <ros/service_traits.h>


#include <nifti_teleop/AcquireRequest.h>
#include <nifti_teleop/AcquireResponse.h>


namespace nifti_teleop
{

struct Acquire
{

typedef AcquireRequest Request;
typedef AcquireResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Acquire
} // namespace nifti_teleop


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nifti_teleop::Acquire > {
  static const char* value()
  {
    return "2543eda9ec3404107775710514498ddf";
  }

  static const char* value(const ::nifti_teleop::Acquire&) { return value(); }
};

template<>
struct DataType< ::nifti_teleop::Acquire > {
  static const char* value()
  {
    return "nifti_teleop/Acquire";
  }

  static const char* value(const ::nifti_teleop::Acquire&) { return value(); }
};


// service_traits::MD5Sum< ::nifti_teleop::AcquireRequest> should match 
// service_traits::MD5Sum< ::nifti_teleop::Acquire > 
template<>
struct MD5Sum< ::nifti_teleop::AcquireRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nifti_teleop::Acquire >::value();
  }
  static const char* value(const ::nifti_teleop::AcquireRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nifti_teleop::AcquireRequest> should match 
// service_traits::DataType< ::nifti_teleop::Acquire > 
template<>
struct DataType< ::nifti_teleop::AcquireRequest>
{
  static const char* value()
  {
    return DataType< ::nifti_teleop::Acquire >::value();
  }
  static const char* value(const ::nifti_teleop::AcquireRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nifti_teleop::AcquireResponse> should match 
// service_traits::MD5Sum< ::nifti_teleop::Acquire > 
template<>
struct MD5Sum< ::nifti_teleop::AcquireResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nifti_teleop::Acquire >::value();
  }
  static const char* value(const ::nifti_teleop::AcquireResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nifti_teleop::AcquireResponse> should match 
// service_traits::DataType< ::nifti_teleop::Acquire > 
template<>
struct DataType< ::nifti_teleop::AcquireResponse>
{
  static const char* value()
  {
    return DataType< ::nifti_teleop::Acquire >::value();
  }
  static const char* value(const ::nifti_teleop::AcquireResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIFTI_TELEOP_MESSAGE_ACQUIRE_H
