// Generated by gencpp from file nifti_teleop/ScanningGoal.msg
// DO NOT EDIT!


#ifndef NIFTI_TELEOP_MESSAGE_SCANNINGGOAL_H
#define NIFTI_TELEOP_MESSAGE_SCANNINGGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nifti_teleop
{
template <class ContainerAllocator>
struct ScanningGoal_
{
  typedef ScanningGoal_<ContainerAllocator> Type;

  ScanningGoal_()
    : action(0)
    , speed(0.0)  {
    }
  ScanningGoal_(const ContainerAllocator& _alloc)
    : action(0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _action_type;
  _action_type action;

   typedef double _speed_type;
  _speed_type speed;



  enum {
    START_SCANNING = 0,
    STOP_SCANNING = 1,
  };


  typedef boost::shared_ptr< ::nifti_teleop::ScanningGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nifti_teleop::ScanningGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ScanningGoal_

typedef ::nifti_teleop::ScanningGoal_<std::allocator<void> > ScanningGoal;

typedef boost::shared_ptr< ::nifti_teleop::ScanningGoal > ScanningGoalPtr;
typedef boost::shared_ptr< ::nifti_teleop::ScanningGoal const> ScanningGoalConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nifti_teleop::ScanningGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nifti_teleop::ScanningGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nifti_teleop

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nifti_teleop': ['/home/elliottwhite/turtlebot2_wss/turtlebot_navigation_ws/devel/share/nifti_teleop/msg'], 'actionlib': ['/opt/ros/kinetic/share/actionlib/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nifti_teleop::ScanningGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nifti_teleop::ScanningGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nifti_teleop::ScanningGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nifti_teleop::ScanningGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nifti_teleop::ScanningGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nifti_teleop::ScanningGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nifti_teleop::ScanningGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0e7f34c8ef5653cd02b0d698e9cea8c";
  }

  static const char* value(const ::nifti_teleop::ScanningGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0e7f34c8ef5653cULL;
  static const uint64_t static_value2 = 0xd02b0d698e9cea8cULL;
};

template<class ContainerAllocator>
struct DataType< ::nifti_teleop::ScanningGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nifti_teleop/ScanningGoal";
  }

  static const char* value(const ::nifti_teleop::ScanningGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nifti_teleop::ScanningGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
byte START_SCANNING=0\n\
byte STOP_SCANNING=1\n\
byte action\n\
float64 speed\n\
";
  }

  static const char* value(const ::nifti_teleop::ScanningGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nifti_teleop::ScanningGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ScanningGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nifti_teleop::ScanningGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nifti_teleop::ScanningGoal_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<int8_t>::stream(s, indent + "  ", v.action);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIFTI_TELEOP_MESSAGE_SCANNINGGOAL_H
