// Generated by gencpp from file nifti_teleop/ScanningResult.msg
// DO NOT EDIT!


#ifndef NIFTI_TELEOP_MESSAGE_SCANNINGRESULT_H
#define NIFTI_TELEOP_MESSAGE_SCANNINGRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nifti_teleop
{
template <class ContainerAllocator>
struct ScanningResult_
{
  typedef ScanningResult_<ContainerAllocator> Type;

  ScanningResult_()
    : result(0)  {
    }
  ScanningResult_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int8_t _result_type;
  _result_type result;



  enum {
    SUCCESS = 0,
    WARNING = 1,
    ERROR = 2,
  };


  typedef boost::shared_ptr< ::nifti_teleop::ScanningResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nifti_teleop::ScanningResult_<ContainerAllocator> const> ConstPtr;

}; // struct ScanningResult_

typedef ::nifti_teleop::ScanningResult_<std::allocator<void> > ScanningResult;

typedef boost::shared_ptr< ::nifti_teleop::ScanningResult > ScanningResultPtr;
typedef boost::shared_ptr< ::nifti_teleop::ScanningResult const> ScanningResultConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nifti_teleop::ScanningResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nifti_teleop::ScanningResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nifti_teleop

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nifti_teleop': ['/home/elliottwhite/turtlebot2_wss/turtlebot_navigation_ws/devel/share/nifti_teleop/msg'], 'actionlib': ['/opt/ros/kinetic/share/actionlib/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nifti_teleop::ScanningResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nifti_teleop::ScanningResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nifti_teleop::ScanningResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nifti_teleop::ScanningResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nifti_teleop::ScanningResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nifti_teleop::ScanningResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nifti_teleop::ScanningResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee33d82383feeada600abc8b124dd43f";
  }

  static const char* value(const ::nifti_teleop::ScanningResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee33d82383feeadaULL;
  static const uint64_t static_value2 = 0x600abc8b124dd43fULL;
};

template<class ContainerAllocator>
struct DataType< ::nifti_teleop::ScanningResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nifti_teleop/ScanningResult";
  }

  static const char* value(const ::nifti_teleop::ScanningResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nifti_teleop::ScanningResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
byte SUCCESS=0\n\
byte WARNING=1\n\
byte ERROR=2\n\
byte result\n\
";
  }

  static const char* value(const ::nifti_teleop::ScanningResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nifti_teleop::ScanningResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ScanningResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nifti_teleop::ScanningResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nifti_teleop::ScanningResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIFTI_TELEOP_MESSAGE_SCANNINGRESULT_H
