// Generated by gencpp from file exploration_msgs/ExplorationPriorityPoint.msg
// DO NOT EDIT!


#ifndef EXPLORATION_MSGS_MESSAGE_EXPLORATIONPRIORITYPOINT_H
#define EXPLORATION_MSGS_MESSAGE_EXPLORATIONPRIORITYPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace exploration_msgs
{
template <class ContainerAllocator>
struct ExplorationPriorityPoint_
{
  typedef ExplorationPriorityPoint_<ContainerAllocator> Type;

  ExplorationPriorityPoint_()
    : header()
    , id(0)
    , position()
    , priority(0.0)
    , action(0)  {
    }
  ExplorationPriorityPoint_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , position(_alloc)
    , priority(0.0)
    , action(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef float _priority_type;
  _priority_type priority;

   typedef uint8_t _action_type;
  _action_type action;



  enum {
    kActionAdd = 0u,
    kActionRemove = 1u,
    kActionRemoveAll = 2u,
  };


  typedef boost::shared_ptr< ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator> const> ConstPtr;

}; // struct ExplorationPriorityPoint_

typedef ::exploration_msgs::ExplorationPriorityPoint_<std::allocator<void> > ExplorationPriorityPoint;

typedef boost::shared_ptr< ::exploration_msgs::ExplorationPriorityPoint > ExplorationPriorityPointPtr;
typedef boost::shared_ptr< ::exploration_msgs::ExplorationPriorityPoint const> ExplorationPriorityPointConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace exploration_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'exploration_msgs': ['/home/elliottwhite/turtlebot2_wss/turtlebot_navigation_ws/src/tradr-msgs/exploration_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cbf08350f3cbaa0d50b6c6b7fb5cf4e7";
  }

  static const char* value(const ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcbf08350f3cbaa0dULL;
  static const uint64_t static_value2 = 0x50b6c6b7fb5cf4e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exploration_msgs/ExplorationPriorityPoint";
  }

  static const char* value(const ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# action types\n\
uint8 kActionAdd       = 0\n\
uint8 kActionRemove    = 1  \n\
uint8 kActionRemoveAll = 2\n\
\n\
# A reference coordinate frame and timestamp\n\
Header header\n\
\n\
uint32 id                     # point id\n\
geometry_msgs/Point position  # position\n\
float32 priority              # priority \n\
uint8 action		      # action type\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.position);
      stream.next(m.priority);
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExplorationPriorityPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "priority: ";
    Printer<float>::stream(s, indent + "  ", v.priority);
    s << indent << "action: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORATION_MSGS_MESSAGE_EXPLORATIONPRIORITYPOINT_H
