// Generated by gencpp from file exploration_msgs/ExplorationPriorityActions.msg
// DO NOT EDIT!


#ifndef EXPLORATION_MSGS_MESSAGE_EXPLORATIONPRIORITYACTIONS_H
#define EXPLORATION_MSGS_MESSAGE_EXPLORATIONPRIORITYACTIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <exploration_msgs/ExplorationPriorityPoint.h>

namespace exploration_msgs
{
template <class ContainerAllocator>
struct ExplorationPriorityActions_
{
  typedef ExplorationPriorityActions_<ContainerAllocator> Type;

  ExplorationPriorityActions_()
    : header()
    , sender(0)
    , num_points(0)
    , priority_points()  {
    }
  ExplorationPriorityActions_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sender(0)
    , num_points(0)
    , priority_points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _sender_type;
  _sender_type sender;

   typedef int32_t _num_points_type;
  _num_points_type num_points;

   typedef std::vector< ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator> >::other >  _priority_points_type;
  _priority_points_type priority_points;



  enum {
    kSenderExplorer = 0u,
    kSenderGUI = 1u,
  };


  typedef boost::shared_ptr< ::exploration_msgs::ExplorationPriorityActions_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exploration_msgs::ExplorationPriorityActions_<ContainerAllocator> const> ConstPtr;

}; // struct ExplorationPriorityActions_

typedef ::exploration_msgs::ExplorationPriorityActions_<std::allocator<void> > ExplorationPriorityActions;

typedef boost::shared_ptr< ::exploration_msgs::ExplorationPriorityActions > ExplorationPriorityActionsPtr;
typedef boost::shared_ptr< ::exploration_msgs::ExplorationPriorityActions const> ExplorationPriorityActionsConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exploration_msgs::ExplorationPriorityActions_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exploration_msgs::ExplorationPriorityActions_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace exploration_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'exploration_msgs': ['/home/elliottwhite/turtlebot2_wss/turtlebot_navigation_ws/src/tradr-msgs/exploration_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::exploration_msgs::ExplorationPriorityActions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exploration_msgs::ExplorationPriorityActions_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration_msgs::ExplorationPriorityActions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration_msgs::ExplorationPriorityActions_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration_msgs::ExplorationPriorityActions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration_msgs::ExplorationPriorityActions_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exploration_msgs::ExplorationPriorityActions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0712cf241eaeffcf9cd15e90cdffcda9";
  }

  static const char* value(const ::exploration_msgs::ExplorationPriorityActions_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0712cf241eaeffcfULL;
  static const uint64_t static_value2 = 0x9cd15e90cdffcda9ULL;
};

template<class ContainerAllocator>
struct DataType< ::exploration_msgs::ExplorationPriorityActions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exploration_msgs/ExplorationPriorityActions";
  }

  static const char* value(const ::exploration_msgs::ExplorationPriorityActions_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exploration_msgs::ExplorationPriorityActions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# sender type\n\
uint8 kSenderExplorer = 0\n\
uint8 kSenderGUI      = 1\n\
\n\
# A reference coordinate frame and timestamp\n\
Header header\n\
\n\
uint8 sender                                # sender type\n\
\n\
int32 num_points	                    # number of points\n\
ExplorationPriorityPoint[] priority_points  # list of priority points with actions\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: exploration_msgs/ExplorationPriorityPoint\n\
# action types\n\
uint8 kActionAdd       = 0\n\
uint8 kActionRemove    = 1  \n\
uint8 kActionRemoveAll = 2\n\
\n\
# A reference coordinate frame and timestamp\n\
Header header\n\
\n\
uint32 id                     # point id\n\
geometry_msgs/Point position  # position\n\
float32 priority              # priority \n\
uint8 action		      # action type\n\
\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::exploration_msgs::ExplorationPriorityActions_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exploration_msgs::ExplorationPriorityActions_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sender);
      stream.next(m.num_points);
      stream.next(m.priority_points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExplorationPriorityActions_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exploration_msgs::ExplorationPriorityActions_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exploration_msgs::ExplorationPriorityActions_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sender: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sender);
    s << indent << "num_points: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_points);
    s << indent << "priority_points[]" << std::endl;
    for (size_t i = 0; i < v.priority_points.size(); ++i)
    {
      s << indent << "  priority_points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::exploration_msgs::ExplorationPriorityPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.priority_points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORATION_MSGS_MESSAGE_EXPLORATIONPRIORITYACTIONS_H
