; Auto-generated. Do not edit!


(cl:in-package networkanalysis_msgs-msg)


;//! \htmlinclude pingactionResult.msg.html

(cl:defclass <pingactionResult> (roslisp-msg-protocol:ros-message)
  ((outp
    :reader outp
    :initarg :outp
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass pingactionResult (<pingactionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <pingactionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'pingactionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name networkanalysis_msgs-msg:<pingactionResult> is deprecated: use networkanalysis_msgs-msg:pingactionResult instead.")))

(cl:ensure-generic-function 'outp-val :lambda-list '(m))
(cl:defmethod outp-val ((m <pingactionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader networkanalysis_msgs-msg:outp-val is deprecated.  Use networkanalysis_msgs-msg:outp instead.")
  (outp m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <pingactionResult>) ostream)
  "Serializes a message object of type '<pingactionResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'outp) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <pingactionResult>) istream)
  "Deserializes a message object of type '<pingactionResult>"
    (cl:setf (cl:slot-value msg 'outp) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<pingactionResult>)))
  "Returns string type for a message object of type '<pingactionResult>"
  "networkanalysis_msgs/pingactionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'pingactionResult)))
  "Returns string type for a message object of type 'pingactionResult"
  "networkanalysis_msgs/pingactionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<pingactionResult>)))
  "Returns md5sum for a message object of type '<pingactionResult>"
  "4646f5e06440d78571c439e8eabcd8d9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'pingactionResult)))
  "Returns md5sum for a message object of type 'pingactionResult"
  "4646f5e06440d78571c439e8eabcd8d9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<pingactionResult>)))
  "Returns full string definition for message of type '<pingactionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool outp~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'pingactionResult)))
  "Returns full string definition for message of type 'pingactionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool outp~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <pingactionResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <pingactionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'pingactionResult
    (cl:cons ':outp (outp msg))
))
