(cl:defpackage exploration_msgs-msg
  (:use )
  (:export
   "<EXPLORATIONPRIORITYACTIONS>"
   "EXPLORATIONPRIORITYACTIONS"
   "<EXPLORATIONPRIORITYPOINT>"
   "EXPLORATIONPRIORITYPOINT"
   "<EXPLORATIONROBOTMESSAGE>"
   "EXPLORATIONROBOTMESSAGE"
  ))

