// Generated by gencpp from file volumetric_msgs/LoadMapInFrameRequest.msg
// DO NOT EDIT!


#ifndef VOLUMETRIC_MSGS_MESSAGE_LOADMAPINFRAMEREQUEST_H
#define VOLUMETRIC_MSGS_MESSAGE_LOADMAPINFRAMEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace volumetric_msgs
{
template <class ContainerAllocator>
struct LoadMapInFrameRequest_
{
  typedef LoadMapInFrameRequest_<ContainerAllocator> Type;

  LoadMapInFrameRequest_()
    : file_path()
    , frame()  {
    }
  LoadMapInFrameRequest_(const ContainerAllocator& _alloc)
    : file_path(_alloc)
    , frame(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _file_path_type;
  _file_path_type file_path;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_type;
  _frame_type frame;





  typedef boost::shared_ptr< ::volumetric_msgs::LoadMapInFrameRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::volumetric_msgs::LoadMapInFrameRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LoadMapInFrameRequest_

typedef ::volumetric_msgs::LoadMapInFrameRequest_<std::allocator<void> > LoadMapInFrameRequest;

typedef boost::shared_ptr< ::volumetric_msgs::LoadMapInFrameRequest > LoadMapInFrameRequestPtr;
typedef boost::shared_ptr< ::volumetric_msgs::LoadMapInFrameRequest const> LoadMapInFrameRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::volumetric_msgs::LoadMapInFrameRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::volumetric_msgs::LoadMapInFrameRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace volumetric_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::volumetric_msgs::LoadMapInFrameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::volumetric_msgs::LoadMapInFrameRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::volumetric_msgs::LoadMapInFrameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::volumetric_msgs::LoadMapInFrameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::volumetric_msgs::LoadMapInFrameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::volumetric_msgs::LoadMapInFrameRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::volumetric_msgs::LoadMapInFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "921a98bd927760f83473e5da2c10f1c9";
  }

  static const char* value(const ::volumetric_msgs::LoadMapInFrameRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x921a98bd927760f8ULL;
  static const uint64_t static_value2 = 0x3473e5da2c10f1c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::volumetric_msgs::LoadMapInFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "volumetric_msgs/LoadMapInFrameRequest";
  }

  static const char* value(const ::volumetric_msgs::LoadMapInFrameRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::volumetric_msgs::LoadMapInFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string file_path\n\
string frame\n\
";
  }

  static const char* value(const ::volumetric_msgs::LoadMapInFrameRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::volumetric_msgs::LoadMapInFrameRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.file_path);
      stream.next(m.frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadMapInFrameRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::volumetric_msgs::LoadMapInFrameRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::volumetric_msgs::LoadMapInFrameRequest_<ContainerAllocator>& v)
  {
    s << indent << "file_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.file_path);
    s << indent << "frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VOLUMETRIC_MSGS_MESSAGE_LOADMAPINFRAMEREQUEST_H
