// Generated by gencpp from file volumetric_msgs/LoadMapInFrame.msg
// DO NOT EDIT!


#ifndef VOLUMETRIC_MSGS_MESSAGE_LOADMAPINFRAME_H
#define VOLUMETRIC_MSGS_MESSAGE_LOADMAPINFRAME_H

#include <ros/service_traits.h>


#include <volumetric_msgs/LoadMapInFrameRequest.h>
#include <volumetric_msgs/LoadMapInFrameResponse.h>


namespace volumetric_msgs
{

struct LoadMapInFrame
{

typedef LoadMapInFrameRequest Request;
typedef LoadMapInFrameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadMapInFrame
} // namespace volumetric_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::volumetric_msgs::LoadMapInFrame > {
  static const char* value()
  {
    return "921a98bd927760f83473e5da2c10f1c9";
  }

  static const char* value(const ::volumetric_msgs::LoadMapInFrame&) { return value(); }
};

template<>
struct DataType< ::volumetric_msgs::LoadMapInFrame > {
  static const char* value()
  {
    return "volumetric_msgs/LoadMapInFrame";
  }

  static const char* value(const ::volumetric_msgs::LoadMapInFrame&) { return value(); }
};


// service_traits::MD5Sum< ::volumetric_msgs::LoadMapInFrameRequest> should match 
// service_traits::MD5Sum< ::volumetric_msgs::LoadMapInFrame > 
template<>
struct MD5Sum< ::volumetric_msgs::LoadMapInFrameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::volumetric_msgs::LoadMapInFrame >::value();
  }
  static const char* value(const ::volumetric_msgs::LoadMapInFrameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::volumetric_msgs::LoadMapInFrameRequest> should match 
// service_traits::DataType< ::volumetric_msgs::LoadMapInFrame > 
template<>
struct DataType< ::volumetric_msgs::LoadMapInFrameRequest>
{
  static const char* value()
  {
    return DataType< ::volumetric_msgs::LoadMapInFrame >::value();
  }
  static const char* value(const ::volumetric_msgs::LoadMapInFrameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::volumetric_msgs::LoadMapInFrameResponse> should match 
// service_traits::MD5Sum< ::volumetric_msgs::LoadMapInFrame > 
template<>
struct MD5Sum< ::volumetric_msgs::LoadMapInFrameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::volumetric_msgs::LoadMapInFrame >::value();
  }
  static const char* value(const ::volumetric_msgs::LoadMapInFrameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::volumetric_msgs::LoadMapInFrameResponse> should match 
// service_traits::DataType< ::volumetric_msgs::LoadMapInFrame > 
template<>
struct DataType< ::volumetric_msgs::LoadMapInFrameResponse>
{
  static const char* value()
  {
    return DataType< ::volumetric_msgs::LoadMapInFrame >::value();
  }
  static const char* value(const ::volumetric_msgs::LoadMapInFrameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VOLUMETRIC_MSGS_MESSAGE_LOADMAPINFRAME_H
