// Generated by gencpp from file volumetric_msgs/SetBoxOccupancyRequest.msg
// DO NOT EDIT!


#ifndef VOLUMETRIC_MSGS_MESSAGE_SETBOXOCCUPANCYREQUEST_H
#define VOLUMETRIC_MSGS_MESSAGE_SETBOXOCCUPANCYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace volumetric_msgs
{
template <class ContainerAllocator>
struct SetBoxOccupancyRequest_
{
  typedef SetBoxOccupancyRequest_<ContainerAllocator> Type;

  SetBoxOccupancyRequest_()
    : box_center()
    , box_size()
    , set_occupied(false)  {
    }
  SetBoxOccupancyRequest_(const ContainerAllocator& _alloc)
    : box_center(_alloc)
    , box_size(_alloc)
    , set_occupied(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _box_center_type;
  _box_center_type box_center;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _box_size_type;
  _box_size_type box_size;

   typedef uint8_t _set_occupied_type;
  _set_occupied_type set_occupied;





  typedef boost::shared_ptr< ::volumetric_msgs::SetBoxOccupancyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::volumetric_msgs::SetBoxOccupancyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetBoxOccupancyRequest_

typedef ::volumetric_msgs::SetBoxOccupancyRequest_<std::allocator<void> > SetBoxOccupancyRequest;

typedef boost::shared_ptr< ::volumetric_msgs::SetBoxOccupancyRequest > SetBoxOccupancyRequestPtr;
typedef boost::shared_ptr< ::volumetric_msgs::SetBoxOccupancyRequest const> SetBoxOccupancyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::volumetric_msgs::SetBoxOccupancyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::volumetric_msgs::SetBoxOccupancyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace volumetric_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::volumetric_msgs::SetBoxOccupancyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::volumetric_msgs::SetBoxOccupancyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::volumetric_msgs::SetBoxOccupancyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::volumetric_msgs::SetBoxOccupancyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::volumetric_msgs::SetBoxOccupancyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::volumetric_msgs::SetBoxOccupancyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::volumetric_msgs::SetBoxOccupancyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6588a1eb7f4c6adf70fa660225beeb92";
  }

  static const char* value(const ::volumetric_msgs::SetBoxOccupancyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6588a1eb7f4c6adfULL;
  static const uint64_t static_value2 = 0x70fa660225beeb92ULL;
};

template<class ContainerAllocator>
struct DataType< ::volumetric_msgs::SetBoxOccupancyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "volumetric_msgs/SetBoxOccupancyRequest";
  }

  static const char* value(const ::volumetric_msgs::SetBoxOccupancyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::volumetric_msgs::SetBoxOccupancyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
geometry_msgs/Vector3 box_center\n\
geometry_msgs/Vector3 box_size\n\
bool set_occupied\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::volumetric_msgs::SetBoxOccupancyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::volumetric_msgs::SetBoxOccupancyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.box_center);
      stream.next(m.box_size);
      stream.next(m.set_occupied);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetBoxOccupancyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::volumetric_msgs::SetBoxOccupancyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::volumetric_msgs::SetBoxOccupancyRequest_<ContainerAllocator>& v)
  {
    s << indent << "box_center: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.box_center);
    s << indent << "box_size: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.box_size);
    s << indent << "set_occupied: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.set_occupied);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VOLUMETRIC_MSGS_MESSAGE_SETBOXOCCUPANCYREQUEST_H
