// Generated by gencpp from file volumetric_msgs/SetDisplayBoundsRequest.msg
// DO NOT EDIT!


#ifndef VOLUMETRIC_MSGS_MESSAGE_SETDISPLAYBOUNDSREQUEST_H
#define VOLUMETRIC_MSGS_MESSAGE_SETDISPLAYBOUNDSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace volumetric_msgs
{
template <class ContainerAllocator>
struct SetDisplayBoundsRequest_
{
  typedef SetDisplayBoundsRequest_<ContainerAllocator> Type;

  SetDisplayBoundsRequest_()
    : min_z(0.0)
    , max_z(0.0)  {
    }
  SetDisplayBoundsRequest_(const ContainerAllocator& _alloc)
    : min_z(0.0)
    , max_z(0.0)  {
  (void)_alloc;
    }



   typedef double _min_z_type;
  _min_z_type min_z;

   typedef double _max_z_type;
  _max_z_type max_z;





  typedef boost::shared_ptr< ::volumetric_msgs::SetDisplayBoundsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::volumetric_msgs::SetDisplayBoundsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetDisplayBoundsRequest_

typedef ::volumetric_msgs::SetDisplayBoundsRequest_<std::allocator<void> > SetDisplayBoundsRequest;

typedef boost::shared_ptr< ::volumetric_msgs::SetDisplayBoundsRequest > SetDisplayBoundsRequestPtr;
typedef boost::shared_ptr< ::volumetric_msgs::SetDisplayBoundsRequest const> SetDisplayBoundsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::volumetric_msgs::SetDisplayBoundsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::volumetric_msgs::SetDisplayBoundsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace volumetric_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::volumetric_msgs::SetDisplayBoundsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::volumetric_msgs::SetDisplayBoundsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::volumetric_msgs::SetDisplayBoundsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::volumetric_msgs::SetDisplayBoundsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::volumetric_msgs::SetDisplayBoundsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::volumetric_msgs::SetDisplayBoundsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::volumetric_msgs::SetDisplayBoundsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "07683f201de683853c90da45e9c9c84a";
  }

  static const char* value(const ::volumetric_msgs::SetDisplayBoundsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x07683f201de68385ULL;
  static const uint64_t static_value2 = 0x3c90da45e9c9c84aULL;
};

template<class ContainerAllocator>
struct DataType< ::volumetric_msgs::SetDisplayBoundsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "volumetric_msgs/SetDisplayBoundsRequest";
  }

  static const char* value(const ::volumetric_msgs::SetDisplayBoundsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::volumetric_msgs::SetDisplayBoundsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 min_z\n\
float64 max_z\n\
";
  }

  static const char* value(const ::volumetric_msgs::SetDisplayBoundsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::volumetric_msgs::SetDisplayBoundsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.min_z);
      stream.next(m.max_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetDisplayBoundsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::volumetric_msgs::SetDisplayBoundsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::volumetric_msgs::SetDisplayBoundsRequest_<ContainerAllocator>& v)
  {
    s << indent << "min_z: ";
    Printer<double>::stream(s, indent + "  ", v.min_z);
    s << indent << "max_z: ";
    Printer<double>::stream(s, indent + "  ", v.max_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VOLUMETRIC_MSGS_MESSAGE_SETDISPLAYBOUNDSREQUEST_H
