// Generated by gencpp from file networkanalysis_msgs/networkdelay.msg
// DO NOT EDIT!


#ifndef NETWORKANALYSIS_MSGS_MESSAGE_NETWORKDELAY_H
#define NETWORKANALYSIS_MSGS_MESSAGE_NETWORKDELAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace networkanalysis_msgs
{
template <class ContainerAllocator>
struct networkdelay_
{
  typedef networkdelay_<ContainerAllocator> Type;

  networkdelay_()
    : rtt(0)
    , delay(0)
    , alive(false)  {
    }
  networkdelay_(const ContainerAllocator& _alloc)
    : rtt(0)
    , delay(0)
    , alive(false)  {
  (void)_alloc;
    }



   typedef int32_t _rtt_type;
  _rtt_type rtt;

   typedef int32_t _delay_type;
  _delay_type delay;

   typedef uint8_t _alive_type;
  _alive_type alive;





  typedef boost::shared_ptr< ::networkanalysis_msgs::networkdelay_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::networkanalysis_msgs::networkdelay_<ContainerAllocator> const> ConstPtr;

}; // struct networkdelay_

typedef ::networkanalysis_msgs::networkdelay_<std::allocator<void> > networkdelay;

typedef boost::shared_ptr< ::networkanalysis_msgs::networkdelay > networkdelayPtr;
typedef boost::shared_ptr< ::networkanalysis_msgs::networkdelay const> networkdelayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::networkanalysis_msgs::networkdelay_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::networkanalysis_msgs::networkdelay_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace networkanalysis_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'networkanalysis_msgs': ['/home/elliottwhite/turtlebot2_wss/turtlebot_navigation_ws/src/tradr-msgs/networkanalysis_msgs/msg', '/home/elliottwhite/turtlebot2_wss/turtlebot_navigation_ws/devel/share/networkanalysis_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::networkanalysis_msgs::networkdelay_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::networkanalysis_msgs::networkdelay_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::networkanalysis_msgs::networkdelay_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::networkanalysis_msgs::networkdelay_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::networkanalysis_msgs::networkdelay_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::networkanalysis_msgs::networkdelay_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::networkanalysis_msgs::networkdelay_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d03f4625e59c7764c5a566890285e1e3";
  }

  static const char* value(const ::networkanalysis_msgs::networkdelay_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd03f4625e59c7764ULL;
  static const uint64_t static_value2 = 0xc5a566890285e1e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::networkanalysis_msgs::networkdelay_<ContainerAllocator> >
{
  static const char* value()
  {
    return "networkanalysis_msgs/networkdelay";
  }

  static const char* value(const ::networkanalysis_msgs::networkdelay_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::networkanalysis_msgs::networkdelay_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#round trip time (rtt) obtained using \"ping\" with ICMO echo request\n\
int32 rtt\n\
\n\
#network delay obtained directly at the application level (ros service call)\n\
int32 delay\n\
\n\
#Flag to check if the link is alive or dead\n\
bool alive\n\
";
  }

  static const char* value(const ::networkanalysis_msgs::networkdelay_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::networkanalysis_msgs::networkdelay_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rtt);
      stream.next(m.delay);
      stream.next(m.alive);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct networkdelay_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::networkanalysis_msgs::networkdelay_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::networkanalysis_msgs::networkdelay_<ContainerAllocator>& v)
  {
    s << indent << "rtt: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rtt);
    s << indent << "delay: ";
    Printer<int32_t>::stream(s, indent + "  ", v.delay);
    s << indent << "alive: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.alive);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NETWORKANALYSIS_MSGS_MESSAGE_NETWORKDELAY_H
