// Generated by gencpp from file networkanalysis_msgs/pingactionGoal.msg
// DO NOT EDIT!


#ifndef NETWORKANALYSIS_MSGS_MESSAGE_PINGACTIONGOAL_H
#define NETWORKANALYSIS_MSGS_MESSAGE_PINGACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace networkanalysis_msgs
{
template <class ContainerAllocator>
struct pingactionGoal_
{
  typedef pingactionGoal_<ContainerAllocator> Type;

  pingactionGoal_()
    : inp(false)  {
    }
  pingactionGoal_(const ContainerAllocator& _alloc)
    : inp(false)  {
  (void)_alloc;
    }



   typedef uint8_t _inp_type;
  _inp_type inp;





  typedef boost::shared_ptr< ::networkanalysis_msgs::pingactionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::networkanalysis_msgs::pingactionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct pingactionGoal_

typedef ::networkanalysis_msgs::pingactionGoal_<std::allocator<void> > pingactionGoal;

typedef boost::shared_ptr< ::networkanalysis_msgs::pingactionGoal > pingactionGoalPtr;
typedef boost::shared_ptr< ::networkanalysis_msgs::pingactionGoal const> pingactionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::networkanalysis_msgs::pingactionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::networkanalysis_msgs::pingactionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace networkanalysis_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'networkanalysis_msgs': ['/home/elliottwhite/turtlebot2_wss/turtlebot_navigation_ws/src/tradr-msgs/networkanalysis_msgs/msg', '/home/elliottwhite/turtlebot2_wss/turtlebot_navigation_ws/devel/share/networkanalysis_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::networkanalysis_msgs::pingactionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::networkanalysis_msgs::pingactionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::networkanalysis_msgs::pingactionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::networkanalysis_msgs::pingactionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::networkanalysis_msgs::pingactionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::networkanalysis_msgs::pingactionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::networkanalysis_msgs::pingactionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "705bdfa3e0e08abae54f3acdf06f1a9d";
  }

  static const char* value(const ::networkanalysis_msgs::pingactionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x705bdfa3e0e08abaULL;
  static const uint64_t static_value2 = 0xe54f3acdf06f1a9dULL;
};

template<class ContainerAllocator>
struct DataType< ::networkanalysis_msgs::pingactionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "networkanalysis_msgs/pingactionGoal";
  }

  static const char* value(const ::networkanalysis_msgs::pingactionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::networkanalysis_msgs::pingactionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
bool inp\n\
";
  }

  static const char* value(const ::networkanalysis_msgs::pingactionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::networkanalysis_msgs::pingactionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.inp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pingactionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::networkanalysis_msgs::pingactionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::networkanalysis_msgs::pingactionGoal_<ContainerAllocator>& v)
  {
    s << indent << "inp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.inp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NETWORKANALYSIS_MSGS_MESSAGE_PINGACTIONGOAL_H
