// Generated by gencpp from file networkanalysis_msgs/pingservice.msg
// DO NOT EDIT!


#ifndef NETWORKANALYSIS_MSGS_MESSAGE_PINGSERVICE_H
#define NETWORKANALYSIS_MSGS_MESSAGE_PINGSERVICE_H

#include <ros/service_traits.h>


#include <networkanalysis_msgs/pingserviceRequest.h>
#include <networkanalysis_msgs/pingserviceResponse.h>


namespace networkanalysis_msgs
{

struct pingservice
{

typedef pingserviceRequest Request;
typedef pingserviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pingservice
} // namespace networkanalysis_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::networkanalysis_msgs::pingservice > {
  static const char* value()
  {
    return "12a26707b8a62d612b0a1ffbc1162d35";
  }

  static const char* value(const ::networkanalysis_msgs::pingservice&) { return value(); }
};

template<>
struct DataType< ::networkanalysis_msgs::pingservice > {
  static const char* value()
  {
    return "networkanalysis_msgs/pingservice";
  }

  static const char* value(const ::networkanalysis_msgs::pingservice&) { return value(); }
};


// service_traits::MD5Sum< ::networkanalysis_msgs::pingserviceRequest> should match 
// service_traits::MD5Sum< ::networkanalysis_msgs::pingservice > 
template<>
struct MD5Sum< ::networkanalysis_msgs::pingserviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::networkanalysis_msgs::pingservice >::value();
  }
  static const char* value(const ::networkanalysis_msgs::pingserviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::networkanalysis_msgs::pingserviceRequest> should match 
// service_traits::DataType< ::networkanalysis_msgs::pingservice > 
template<>
struct DataType< ::networkanalysis_msgs::pingserviceRequest>
{
  static const char* value()
  {
    return DataType< ::networkanalysis_msgs::pingservice >::value();
  }
  static const char* value(const ::networkanalysis_msgs::pingserviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::networkanalysis_msgs::pingserviceResponse> should match 
// service_traits::MD5Sum< ::networkanalysis_msgs::pingservice > 
template<>
struct MD5Sum< ::networkanalysis_msgs::pingserviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::networkanalysis_msgs::pingservice >::value();
  }
  static const char* value(const ::networkanalysis_msgs::pingserviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::networkanalysis_msgs::pingserviceResponse> should match 
// service_traits::DataType< ::networkanalysis_msgs::pingservice > 
template<>
struct DataType< ::networkanalysis_msgs::pingserviceResponse>
{
  static const char* value()
  {
    return DataType< ::networkanalysis_msgs::pingservice >::value();
  }
  static const char* value(const ::networkanalysis_msgs::pingserviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NETWORKANALYSIS_MSGS_MESSAGE_PINGSERVICE_H
