// Generated by gencpp from file networkanalysis_msgs/wirelesslink.msg
// DO NOT EDIT!


#ifndef NETWORKANALYSIS_MSGS_MESSAGE_WIRELESSLINK_H
#define NETWORKANALYSIS_MSGS_MESSAGE_WIRELESSLINK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace networkanalysis_msgs
{
template <class ContainerAllocator>
struct wirelesslink_
{
  typedef wirelesslink_<ContainerAllocator> Type;

  wirelesslink_()
    : rssi(0)
    , lqi(0)
    , noise(0)  {
    }
  wirelesslink_(const ContainerAllocator& _alloc)
    : rssi(0)
    , lqi(0)
    , noise(0)  {
  (void)_alloc;
    }



   typedef int16_t _rssi_type;
  _rssi_type rssi;

   typedef int16_t _lqi_type;
  _lqi_type lqi;

   typedef int16_t _noise_type;
  _noise_type noise;





  typedef boost::shared_ptr< ::networkanalysis_msgs::wirelesslink_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::networkanalysis_msgs::wirelesslink_<ContainerAllocator> const> ConstPtr;

}; // struct wirelesslink_

typedef ::networkanalysis_msgs::wirelesslink_<std::allocator<void> > wirelesslink;

typedef boost::shared_ptr< ::networkanalysis_msgs::wirelesslink > wirelesslinkPtr;
typedef boost::shared_ptr< ::networkanalysis_msgs::wirelesslink const> wirelesslinkConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::networkanalysis_msgs::wirelesslink_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::networkanalysis_msgs::wirelesslink_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace networkanalysis_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'networkanalysis_msgs': ['/home/elliottwhite/turtlebot2_wss/turtlebot_navigation_ws/src/tradr-msgs/networkanalysis_msgs/msg', '/home/elliottwhite/turtlebot2_wss/turtlebot_navigation_ws/devel/share/networkanalysis_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::networkanalysis_msgs::wirelesslink_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::networkanalysis_msgs::wirelesslink_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::networkanalysis_msgs::wirelesslink_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::networkanalysis_msgs::wirelesslink_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::networkanalysis_msgs::wirelesslink_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::networkanalysis_msgs::wirelesslink_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::networkanalysis_msgs::wirelesslink_<ContainerAllocator> >
{
  static const char* value()
  {
    return "457a5c2625e82fb0b67b1de1eee53435";
  }

  static const char* value(const ::networkanalysis_msgs::wirelesslink_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x457a5c2625e82fb0ULL;
  static const uint64_t static_value2 = 0xb67b1de1eee53435ULL;
};

template<class ContainerAllocator>
struct DataType< ::networkanalysis_msgs::wirelesslink_<ContainerAllocator> >
{
  static const char* value()
  {
    return "networkanalysis_msgs/wirelesslink";
  }

  static const char* value(const ::networkanalysis_msgs::wirelesslink_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::networkanalysis_msgs::wirelesslink_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Received Signal Strength (RSS) in dBm\n\
int16 rssi\n\
\n\
#Link Quality of the wireless link in percentage\n\
int16 lqi\n\
\n\
#Noise floor of the wireless link in dBm (only very few NICs provide this correctly)\n\
int16 noise\n\
";
  }

  static const char* value(const ::networkanalysis_msgs::wirelesslink_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::networkanalysis_msgs::wirelesslink_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rssi);
      stream.next(m.lqi);
      stream.next(m.noise);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wirelesslink_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::networkanalysis_msgs::wirelesslink_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::networkanalysis_msgs::wirelesslink_<ContainerAllocator>& v)
  {
    s << indent << "rssi: ";
    Printer<int16_t>::stream(s, indent + "  ", v.rssi);
    s << indent << "lqi: ";
    Printer<int16_t>::stream(s, indent + "  ", v.lqi);
    s << indent << "noise: ";
    Printer<int16_t>::stream(s, indent + "  ", v.noise);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NETWORKANALYSIS_MSGS_MESSAGE_WIRELESSLINK_H
